# --- Site Settings ---
title: Yixin's Blog
description: "https://www.yixinxu.xyz"
author: Yixin Xu
  links:
      - label: "Email"
        url: "mailto:yixinxu0306@gmail.com"
      # - label: "GitHub"                 <-- ADD # HERE TO HIDE IT
      #   icon: "fab fa-fw fa-github"     <-- ADD # HERE TOO
      #   url: "https://github.com/yourname"
url: "https://www.yixinxu.xyz" # Replace with your actual link
layout: single # Title is at the top

# --- Theme Setup ---
# If using the standard theme:
theme: jekyll-theme-minimal

# If using the "Minimal Mistakes" theme (Recommended for Math):
# remote_theme: "mmistakes/minimal-mistakes"

# --- Math Support (Crucial!) ---
markdown: kramdown
kramdown:
  math_engine: mathjax

# --- Navigation ---
# This makes your sidebar work
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
